const categoriasInitialData = [
  {
    nome: "apartamento",
    cor: "bg-danger",
    icone: "house",
    tipo: "Gastos Essenciais",
  },
  {
    nome: "alimentação",
    cor: "bg-danger",
    icone: "utensils",
    tipo: "Gastos Essenciais",
  },
  {
    nome: "saúde mental",
    cor: "bg-danger",
    icone: "user-doctor",
    tipo: "Gastos Essenciais",
  },
  {
    nome: "cursos e educação",
    cor: "bg-danger",
    icone: "graduation-cap",
    tipo: "Gastos Essenciais",
  },
  {
    nome: "internet",
    cor: "bg-danger",
    icone: "wifi",
    tipo: "Gastos Essenciais",
  },
  {
    nome: "academia",
    cor: "bg-danger",
    icone: "dumbbell",
    tipo: "Gastos Essenciais",
  },
  {
    nome: "imposto",
    cor: "bg-danger",
    icone: "circle-dollar-to-slot",
    tipo: "Gastos Essenciais",
  },
  {
    nome: "saúde",
    cor: "bg-danger",
    icone: "hospital",
    tipo: "Gastos Essenciais",
  },
  {
    nome: "café",
    cor: "bg-primary",
    icone: "mug-hot",
    tipo: "Gastos",
  },
  {
    nome: "viagem",
    cor: "bg-primary",
    icone: "plane",
    tipo: "Gastos",
  },
  {
    nome: "restaurante",
    cor: "bg-primary",
    icone: "champagne-glasses",
    tipo: "Gastos",
  },
  {
    nome: "transporte",
    cor: "bg-primary",
    icone: "car",
    tipo: "Gastos",
  },
  {
    nome: "livros",
    cor: "bg-primary",
    icone: "book-open",
    tipo: "Gastos",
  },
  {
    nome: "papelaria",
    cor: "bg-primary",
    icone: "paperclip",
    tipo: "Gastos",
  },
  {
    nome: "telefone",
    cor: "bg-primary",
    icone: "phone",
    tipo: "Gastos",
  },
  {
    nome: "roupas",
    cor: "bg-primary",
    icone: "shirt",
    tipo: "Gastos",
  },
  {
    nome: "decoração",
    cor: "bg-primary",
    icone: "box",
    tipo: "Gastos",
  },
  {
    nome: "farmácia",
    cor: "bg-primary",
    icone: "pills",
    tipo: "Gastos",
  },
  {
    nome: "presente",
    cor: "bg-primary",
    icone: "gift",
    tipo: "Gastos",
  },
  {
    nome: "lazer",
    cor: "bg-primary",
    icone: "bowling-ball",
    tipo: "Gastos",
  },
  {
    nome: "salão de beleza",
    cor: "bg-primary",
    icone: "scissors",
    tipo: "Gastos",
  },
  {
    nome: "correios",
    cor: "bg-primary",
    icone: "truck",
    tipo: "Gastos",
  },
  {
    nome: "salário",
    cor: "bg-success",
    icone: "dollar-sign",
    tipo: "Receitas",
  },
  {
    nome: "aluguel",
    cor: "bg-success",
    icone: "dollar-sign",
    tipo: "Receitas",
  },
  {
    nome: "devolução",
    cor: "bg-success",
    icone: "dollar-sign",
    tipo: "Receitas",
  },
  {
    nome: "freelance",
    cor: "bg-success",
    icone: "dollar-sign",
    tipo: "Receitas",
  },
  {
    nome: "não contabilizar",
    cor: "bg-dark",
    icone: "dollar-sign",
    tipo: "Não Contabilizar",
  },
  {
    nome: "sem categoria",
    cor: "bg-dark",
    icone: "dollar-sign",
    tipo: "Gastos",
  },
  {
    nome: "outros",
    cor: "bg-primary",
    icone: "dollar-sign",
    tipo: "Gastos",
  },
  {
    nome: "pagamento de fatura",
    cor: "bg-primary",
    icone: "dollar-sign",
    tipo: "Gastos",
  },
  {
    nome: "retorno de empréstimo",
    cor: "bg-primary",
    icone: "dollar-sign",
    tipo: "Receitas",
  },
  {
    nome: "doação",
    cor: "bg-primary",
    icone: "hand-holding-heart",
    tipo: "Gastos",
  },
  {
    nome: "eletrônicos",
    cor: "bg-primary",
    icone: "computer",
    tipo: "Gastos",
  },
  {
    nome: "entretenimento",
    cor: "bg-primary",
    icone: "ticket",
    tipo: "Gastos",
  },
  {
    nome: "supermercado",
    cor: "bg-primary",
    icone: "cart-shopping",
    tipo: "Gastos",
  },
  {
    nome: "transferência enviada",
    cor: "bg-primary",
    icone: "dollar-sign",
    tipo: "Gastos",
  },
  {
    nome: "transferência recebida",
    cor: "bg-success",
    icone: "dollar-sign",
    tipo: "Receitas",
  },
];

module.exports = categoriasInitialData;
